<style>
.videoWrapper {
  position: relative;
  padding-bottom: 56.25%; /* 16:9 */
  padding-top: 25px;
  height: 0;
}
.videoWrapper iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

</style>
<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td><h3>About izberg</h3></td>
        </tr>
    </tbody></table>
</div>

<div class="entity-edit" id="matage-options-panel">
    <div class="entry-edit-head">
    <h4>Izberg Marketplace</h4>
    </div>
    <div>
      <p>
        Izberg Marketplace is a SaaS (Software as a service) technology, allowing you to open a multi-seller e-commerce platform in just a few clicks. The izberg environment is a platform where sellers and application managers meet and link their business to each other’s. The roles are split between the marketplace operator who manage his e-commerce website through his application, and the sellers who manage their products, stocks, and all the delivery process. As an Izberg marketplace operator, you are able to pick the sellers you want among those who are already part of the izberg environment, and more generally, manage an e-commerce platform without worrying about stocks and delivery.
      </p>
    </div>
    <div class="box">
        <div class="videoWrapper">
          <iframe width="620" height="415" src="http://www.youtube.com/embed/OYDICSZCPm0"></iframe>
        </div>
    </div>
</div>
