<div class="box">
    <strong>
        <?php echo $this->__("You can use our tutorial to help you to setup izberg on your magento website : ")?>
        <a href="<?php echo Mage::helper("adminhtml")->getUrl("izberg/adminhtml_help/tutorial");?>">
            <?php echo $this->__("Here")?>
        </a>
    </strong>
    <br />
    <strong>
        <?php echo $this->__("You can follow importation status from job list page : ")?>
        <a href="<?php echo Mage::helper("adminhtml")->getUrl("izberg/adminhtml_job");?>">
            <?php echo $this->__("Here")?>
        </a>
    </strong>
</div>
