<?php
/**
 * Cybage Signup Promotion Plugin 
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will  send you a copy of the source file.
 *
 * @category   Signup Promotion Plugin
 * @package    Cybage_SignupPromo
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */

$couponData = $this->getCouponData();
?>
<div class="page-title">
    <h1><?php echo $this->__('My Coupons') ?></h1>
</div>
<?php if( count($couponData->getData()) > 0 ): ?>
<table class="data-table" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th>Coupon #</th>
            <th>Expiry Date</th>
            <th>Offer</th>
            <th><span class="nobr">Used</span></th>
            <th><span class="nobr">Times Used</span></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($couponData as $val): ?>
        <tr>
        <td><?php echo $this->__($val->getCode()) ?></td>
            <td><span class="nobr"><?php echo $this->__(date('d-m-Y',strtotime($val->getExpirationDate()))) ?></span></td>
            <td><?php echo $this->__($val->getDescription()) ?></td>
            <td><span class="price"><?php echo $this->__($val->getTimesUsed() > 0 ? 'yes':'no') ?></span></td>
            <td><em><?php echo $this->__($val->getTimesUsed()) ?></em></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
    <p><?php echo $this->__('You have no coupons.'); ?></p>
<?php endif; ?>
