<?php if (isset($foxrateFiError)):?>
    <div class="info-box"><?php echo $foxrateFiError; ?></div>
<?php else:?>

    <ul class="fi-user-reviews">
        <?php foreach ($viewHelper->getProductReviewList($productId) as $review):?>
            <li itemprop="review" itemscope itemtype="http://schema.org/Review">
                <div class="fi-user-review">
                    <div class="fi-row fi-user-rating">
                <span itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                    <meta itemprop="worstRating" content = "5"/>
                    <meta itemprop="ratingValue" content = "{$review->ratings->overall}"/>
                    <meta itemprop="bestRating" content = "1"/>
                </span>
                        <div class="fi-rating-stars" data-rating="<?php echo Mage::helper('reviewcoreintegration')->formatCalcPercent($review->ratings->overall, 5); ?>"><span class="fi-indicator"></span></div>
                        <div class="fi-user-name">
                            <?php
                            $fiUser = $this->htmlEscape($review->writer->name);
                            if (!$fiUser) $fiUser = $this->__('Anonymous');
                            echo $this->__('FOXRATE_REVIEW_BY').' <b>'.$this->__('<span itemprop="author" class="fi-srong">%s.</span>', $fiUser).'</b>'; ?>
                        </div>
                        <div class="fi-user-date">
                            <?php echo $this->__('FOXRATE_POSTED_ON'); ?>:
                    <span class="fi-strong">
                        <meta itemprop="datePublished" content="<?php echo $review->created->format('Y-m-d'); ?>">
                        <?php echo $review->created->format('d.m.Y'); ?>
                        </meta>
                    </span>
                        </div>
                    </div>

                    <div class="fi-row fi-pros-n-cons">
                        <?php if (!empty($review->texts->pros)): ?>
                            <div class="fi-column fi-column-50 fi-column-left">
                                <div class="fi-value-label fi-strong">
                                    <?php echo $this->__('FOXRATE_PROS'); ?>
                                </div>
                                <div class="fi-user-arguments">
                                    <?php echo $review->texts->pros ?>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php if (!empty($review->texts->cons)): ?>
                            <div class="fi-column fi-column-50 fi-column-left">
                                <div class="fi-value-label fi-strong">
                                    <?php echo $this->__('FOXRATE_CONS'); ?>
                                </div>
                                <div class="fi-user-arguments">
                                    <?php echo $review->texts->cons ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="fi-user-comment fi-row">
                        <div class="fi-column fi-column-50 fi-column-left" itemprop="description">
                            <?php if (!empty($review->texts->comment)): ?>
                                <div class="fi-value-label fi-strong">
                                    <?php echo $this->__('Comment'); ?>
                                </div>
                                <div class="fi-user-arguments">
                                    <?php echo $review->texts->comment; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="fi-column fi-column-50 fi-column-left" itemprop="name">
                            <?php if (!empty($review->texts->conclusion)): ?>
                                <div class="fi-value-label fi-strong">
                                    <?php echo $this->__('Conclusion'); ?>
                                </div>
                                <div class="fi-user-arguments">
                                    <?php echo $review->texts->conclusion; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="fi-user-comment fi-row">
                        <div class="fi-column fi-column-100">
                            <div class="fi-value-label fi-strong">
                                <?php echo ucfirst($this->__('FOXRATE_REOMMEND2')); ?>:
                                <span class="fi-normal">
                                    <?php if ($review->recommends == 1): ?>
                                        <?php echo $this->__('FOXRATE_YES'); ?>
                                    <?php else:?>
                                        <?php echo $this->__('FOXRATE_NO'); ?>
                                    <?php endif; ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>

<?php endif; ?>