<?php echo $this->getLayout()->getBlockSingleton('review/form')->setTemplate('foxrate/review/foxrate_general_details.phtml')->toHtml(); ?>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/fi-scripts-sdk.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/fi-scripts.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/modalbox/js/jquery.modalbox-1.4.1.js')?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('js/foxrate/modalbox/css/jquery.modalbox.css')?>" media="all" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/fi-style.css')?>" media="all" />