<?php
if ($reviewTotals->getReviewsCount()): ?>
    <div class="_ratings">
        <? if ($reviewTotals->getTotalReviews() > 0): ?>
            <?php echo $ratingHelper->getRatingStars($this->getEntityId()); ?>
        <? endif; ?>

        <?php if (!isset($reviewLink)): ?>
            <p class="rating-links">
                <a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%d Review(s)', $reviewTotals->getReviewsCount()) ?></a>
            </p>
        <?php else: ?>

            <?php
            //Strangely: leaving like in original p tag it breaks html ( <p class="rating-links"> )
            ?>
            <div class="rating-links">
                <?php if (isset($addReviewsLink)): ?>
                    <a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%d Review(s)', $reviewTotals->getReviewsCount()) ?></a>
                <?php else: ?>
                    <?php echo $this->__('%d Review(s)', $reviewTotals->getReviewsCount()) ?>
                <?php endif; ?>

                <span class="separator">|</span>
                <a id='writeReviews' class='openmodalbox' href='javascript:void(0);'><?php echo $this->__('FOXRATE_WRITE_REV'); ?>
                    <span class='modalboxContent'>
                        <div id='outterContainer' class='outterContainer' scrolling='no'>
                            <iframe class='foxrateProductProfile' id='foxrateProductProfile' height='770' width='1050' src='<?php echo $reviewLink; ?>'></iframe>
                        </div>
                    </span>
                </a>
            </div>
        <?php endif; ?>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/fi-scripts-sdk.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/fi-scripts.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/modalbox/js/jquery.modalbox-1.4.1.js')?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('js/foxrate/modalbox/css/jquery.modalbox.css')?>" media="all" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/fi-style.css')?>" media="all" />