<?php
/**
 * Currently this case is not complete, so we simply show empty.phtml which shows nothing.
 */
?>
<a id='writeReviews' class='openmodalbox reviewTitle' href='javascript:void(0);'><?php echo $this->__('Be the first to review this product'); ?>
    <span class='modalboxContent'>
        <div id='outterContainer' class='outterContainer' scrolling='no'>
            <iframe class='foxrateProductProfile' id='foxrateProductProfile' height='770' width='1050' src='<?php echo $reviewLink; ?>'></iframe>
        </div>
    </span>
</a>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/jquery.1.8.3.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/foxrateProdRev.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/foxrate/modalbox/js/jquery.modalbox-1.4.1.js')?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('js/foxrate/modalbox/css/jquery.modalbox.css')?>" media="all" />
