<?php

$helper = Mage::helper('onestepcheckout/checkout');
    $billingFields['firstname'] = '
        <div class="input-box input-firstname'.((in_array('firstname', $this->formErrors['billing_errors'])) ? ' input-error' : '').'">
            <label for="billing:firstname">'.$this->__('First Name').'<span class="required">*</span></label><br />
            <input class="required-entry input-text" type="text" name="billing[firstname]" id="billing:firstname" value="'.$this->getFirstname().'" />
        </div>';
    $billingFields['lastname'] = '
        <div class="input-box input-lastname'.((in_array('lastname', $this->formErrors['billing_errors'])) ? ' input-error' : '').'">
            <label for="billing:lastname">'.$this->__('Last Name').' <span class="required">*</span></label><br />
            <input class="required-entry input-text" type="text" name="billing[lastname]" id="billing:lastname" value="'.$this->getLastname().'" />
        </div>';
?>
<?php if(!$this->isCustomerLoggedIn()): ?>
    <?php $billingFields['email'] = '
        <div class="input-box input-email'.((in_array('email', $this->formErrors['billing_errors'])) ? ' input-error' : '').'">
            <label for="billing:email">'.$this->__('Email Address').' <span class="required">*</span></label><br />
            <input type="text" name="billing[email]" id="billing:email" value="'.$this->htmlEscape($this->getAddress()->getEmail()).'" title="'.$this->__('Email Address') .'" class="validate-email required-entry input-text" />
        </div>';
    ?>
<?php endif; ?>
<?php if(!$this->isCustomerLoggedIn() || in_array('email_registered', $this->formErrors['billing_errors'])): ?>
    <?php $billingFields['email_error'] = '
        <div class="clearfix" id="onestepcheckout-email-error" '.((!in_array('email_registered', $this->formErrors['billing_errors'])) ? 'style="display: none"' : '').'>
            <div id="onestepcheckout-email-error-message" class="onestepcheckout-error">'.
                ((in_array('email_registered', $this->formErrors['billing_errors'])) ? $this->__('Email address already registered. Please <a href="#" onclick="login_popup.show(); return false;">login now</a> or use a different email address.') : $this->__('Invalid email address.'))
            .'</div>
        </div>';
    ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_telephone']):?>
    <?php $billingFields['telephone'] = '
        <div class="input-box input-telephone'.((in_array('telephone', $this->formErrors['billing_errors'])) ? ' input-error' : '').'">
            <label for="billing:telephone">'.$this->__('Telephone').' <span class="required">*</span></label><br/>
            <input type="text" name="billing[telephone]" value="'.$this->htmlEscape($this->getTelephone()).'" title="'.$this->__('Telephone').'" class="required-entry input-text" id="billing:telephone" />
        </div>';
    ?>
<?php endif; ?>
<?php if(!$this->settings['exclude_address']):?>
<?php
$addressFields = '';
    for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++){

    		$addressFields .= '<input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$this->htmlEscape($this->getStreet($_i)).'" class="'.(($_i == 1)? 'required-entry ' : '').'input-text onestepcheckout-address-line" style="display:none"/>';
            $addressFields .= (($_i != $this->helper('customer/address')->getStreetLines()) ? '<br/>': '');
    }
    $billingFields['street'] = '
        <div class="input-box input-address'.((in_array('telephone', $this->formErrors['billing_errors'])) ? ' input-error' : '').'">
            <label for="billing:street">'.$this->__('FIFA Ultimate Team Name:').'<span class="required">*</span></label><br />
            <input type="text" name="billing[street][]"  title="'.$this->__('FIFA Ultimate Team Name:').'" class="required-entry input-text" id="billing:street1" />
    </div>';
?>
<?php endif; ?>

<?php if(!$this->settings['exclude_country_id']):?>
<?php
$billingFields['country_id'] = '
    <div class="input-box input-country'.((in_array('country', $this->formErrors['billing_errors'])) ? ' input-error' : '').'" style="display: none">
        <label for="billing:country_id">'.$this->__('Country').' <span class="required">*</span></label><br />
            '.$this->getCountryHtmlSelect('billing').'
    </div>';
?>
<?php else: ?>
<?php $billingFields['country_id'] = '
    <input type="hidden" name="billing[country_id]" id="billing:country_id" value="'.$this->settings['default_country'].'" style="display: none"/>';
?>
<?php endif; ?>
<?php if(!$this->settings['exclude_region']): ?>
<?php 

$region=$this->escapeHtml($this->getAddress()->getRegion()); 

$regiontitle= Mage::helper('core')->quoteEscape($this->__('State/Province'));

$regiontext= $this->helper('customer/address')->getAttributeValidationClass('region');

?>
    <?php $billingFields['region_id'] = '
        <div class="input-box input-region'.((in_array('region', $this->formErrors['billing_errors'])) ? ' input-error' : '').' ">
            <label for="billing:region">'.$this->__('Player Position:').' <span class="required">*</span></label><br/>
                <select id="billing:region_id" name="billing[region_id]"  title="State/Province" class="validate-select" style="display:none;">
                                <option value="">'.$this->__('Please select region, state or province').'</option>
                            </select>
				<input type="text" id="billing:region" name="billing[region]" value="test"  title="State/Province" class="input-text '.$regiontext.' style="display:none;" />
			 </div>';
    ?>
<?php endif; ?>
<?php if(!$this->settings['exclude_city']):?>
    <?php $billingFields['city'] = '
        <div class="input-box input-city'.((in_array('city', $this->formErrors['billing_errors'])) ? ' input-error' : '').'">
            <label for="billing:city">'.$this->__('Player name:').' <span class="required">*</span></label><br/>
            <input type="text" name="billing[city]"  title="'.$this->__('Player name').'" class="required-entry input-text" id="billing:city" />
        </div>';
    ?>
<?php endif; ?>

<?php if(!$this->settings['exclude_zip']): ?>
    <?php $billingFields['postcode'] = '
        <div class="input-box input-postcode'.((in_array('postcode', $this->formErrors['billing_errors'])) ? ' input-error' : '').'" >
            <label for="billing:postcode">'.$this->__('Player Level:').' <span class="required">*</span></label><br />
            <select name="billing[postcode]" title="'.$this->__('Player Level').'" class="validate-select" id="billing:postcode" >
                <option value="">'.$this->__('Please Select...').'</option>
				<option value="Bronze">'.$this->__('Bronze').'</option>
				<option value="Silver">'.$this->__('Silver').'</option>
				<option value="Gold">'.$this->__('Gold').'</option>
            </select>
		</div>';
    ?>
<?php endif; ?>

 
<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat'); ?>
<?php if($_taxvat->isEnabled()): ?>
    <?php $billingFields['taxvat'] =
            $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())
                ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
    ?>
<?php endif; ?>

<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>

<?php if ($_dob && $_dob->isEnabled()): ?>
    <?php $billingFields['dob'] = '
        <div class="field">
            '.$_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div>.';
    ?>
<?php endif; ?>
<?php if ($_gender && $_gender->isEnabled()): ?>
    <?php $billingFields['gender'] = '
        <div class="field">
            '.$_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div>';
    ?>
<?php endif ?>



<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
    <?php $billingFields['save_in_address_book'] = '
        <li class="control">
            <input type="checkbox" name="billing[save_in_address_book]" value="1" title="'.$this->__('Save in address book').'" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);"'.(($this->getAddress()->getSaveInAddressBook()) ? 'checked="checked"':'').' class="checkbox" /><label for="billing:save_in_address_book">'.$this->__('Save in address book').'</label>
        </li>';
    ?>
<?php else:?>
    <?php $billingFields['save_in_address_book'] = '
        <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>';
    ?>
<?php endif; ?>

<?php $billingFields = $this->getBillingFieldsOrder($billingFields);?>
<?php foreach($billingFields as $key => $value):?>
    <?php if(!empty($value['has_li'])):?>
        <?php echo implode('',$value['fields']);?>
    <?php else:?>
        <li class="clearfix"><?php echo implode('',$value['fields']);?></li>
    <?php endif;?>
<?php endforeach; ?>

<?php 

//echo "<select id='billing:region_id' name='billing[region_id]' style='display:none;'><option value='test'>test</option></select>";


//echo "<input type='hidden' id='billing:region_id' name='billing[region_id]' value='3' />";

?>
 


 
 
 