<?php 
/**
 * @category    Development
 * @package     Singsys_Fbconnect
 * @version     1.0.0
 * @copyright   Copyright (c) 2015 SingsysShop (https://www.singsys.com)
 * @author	Singsys
 */
?>

<div class="singsys-fbconnect-account">
    <div class="page-title">
        <h1><?php echo $this->__('Connect Via Facebook') ?></h1>
    </div>

    <?php if($this->_hasUserInfo()): ?>

    <?php
        $googleId = $this->_getFacebookId();
        $status = $this->_getStatus();
        $email = $this->_getEmail();
        $name = $this->_getName();
        $picture = $this->_getPicture();
        $gender = $this->_getGender();
        $birthday = $this->_getBirthday();
    ?>

    <div class="col3-set">
        <div class="box">
            <div class="box-content">
                <div class="col-1">
                    <?php if(!empty($picture)): ?>
                    <p>
                        <img src="<?php echo $picture; ?>" alt="<?php echo $this->htmlEscape($name); ?>" />
                    </p>
                    <?php endif; ?>
                </div>
                <div class="col-2">
                    <?php if(!empty($status)): ?>
                    <p>
                        <?php printf($this->__('Connected as %s', '<strong>'.$status.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($email)): ?>
                    <p>
                        <?php printf($this->__('Email: %s', '<strong>'.$email.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($googleId)): ?>
                    <p>
                        <?php printf($this->__('Facebook #: %s', '<strong>'.$googleId.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($gender)): ?>
                    <p>
                        <?php printf($this->__('Gender: %s', '<strong>'.$gender.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($birthday)): ?>
                    <p>
                        <?php printf($this->__('Birthday: %s', '<strong>'.$birthday.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                </div>
                <div class="col-3">
                    <?php echo $this->getChildHtml('singsys_fbconnect_account_facebook_button'); ?>
                </div>
            </div>
        </div>
    </div>
    <?php else: ?>
    <div class="col2-set">
        <div class="box-content">
            <div class="col-1">
                <p>
                    <?php echo $this->__('You can connect store account with your Facebook account so you could login easier in the future.') ?>
                </p>
            </div>
            <div class="col-2">
                <?php echo $this->getChildHtml('singsys_fbconnect_account_facebook_button'); ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>
