<?php 
/**
 * @category    Development
 * @package     Singsys_Fbconnect
 * @version     1.0.0
 * @copyright   Copyright (c) 2015 SingsysShop (https://www.singsys.com)
 * @author	Singsys
 */
?>

<div class="clearer">
    <div class="singsys-fbconnect-facebook">
        <div class="singsys-fbconnect-facebook-inner">
            <a href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>"><?php echo $this->_getButtonText(); ?></a>
        </div>
        <div class="singsys-fbconnect-facebook-right"></div>
    </div>
</div>
